language: generic
sudo: required
services:
  - docker

before-install:
  - docker build -t vijayamahesh/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vijayamahesh/docker-react npm run test